export const rmTankData = [
    { id: 1, name: 'Betain Tank Level', value: 76.85, unit: '%', status: 'success' },
    { id: 2, name: 'Benzyl Tank Level', value: 1173.55, unit: 'KG', status: 'success' },
    { id: 3, name: 'DM5500 Tote Level', value: 20.32, unit: '%', status: 'error' },
    { id: 4, name: 'DM5500 Tank Level', value: 5108.52, unit: 'KG', status: 'success' },
    { id: 5, name: 'Kathon Tank Level', value: 389.62, unit: 'KG', status: 'success' },
    { id: 6, name: 'HCBase Tank Level', value: 8542.00, unit: 'KG', status: 'success' },
    { id: 7, name: 'SLS Tanka Level', value: 42.32, unit: '%', status: 'warning' },
    { id: 8, name: 'SLS Tankb Level', value: 39.81, unit: '%', status: 'warning' },
    { id: 9, name: 'SLE3S Tanka Level', value: 84.40, unit: '%', status: 'success' },
    { id: 10, name: 'SLE3S Tankb Level', value: 87.64, unit: '%', status: 'success' },
    { id: 11, name: '1.25 Tank Level', value: 9.80, unit: 'KG', status: 'error' },
    { id: 12, name: 'Climbazole Tank1 Level', value: 1997.37, unit: 'KG', status: 'success' },
    { id: 13, name: 'HAS Tank Level', value: 41.70, unit: '%', status: 'warning' },
    { id: 14, name: 'HOTDI Tank Level', value: 94.61, unit: '%', status: 'success' },
    { id: 15, name: 'COLDDI Tank Level', value: 89.72, unit: '%', status: 'success' },
    { id: 16, name: 'LPBase Tank Level', value: 5945.50, unit: 'KG', status: 'success' },
];

export const ttsTankData = [
    { id: 1, batchId: 'CH192', brand: 'BRAND_NAME', date: 'Sunday, September 21, 2025', status: 'Sanitization Due', color: 'black' },
    { id: 2, batchId: 'CH239', brand: 'BRAND_NAME', date: 'Sunday, September 21, 2025', status: 'Packing Transfer', color: 'magenta' },
    { id: 3, batchId: 'CH223', brand: 'BRAND_NAME', date: 'Friday, September 19, 2025', status: 'Dirty', color: 'cyan' },
    { id: 4, batchId: 'CH222', brand: 'BRAND_NAME', date: 'Wednesday, September 10, 2025', status: 'Packing Transfer', color: 'purple' },
    { id: 5, batchId: 'CH248', brand: 'BRAND_NAME', date: 'Friday, September 19, 2025', status: 'Approve', color: 'lime' },
    { id: 6, batchId: 'CH239', brand: 'BRAND_NAME', date: 'Sunday, September 21, 2025', status: 'Approve', color: 'green' },
    { id: 7, batchId: 'CH100', brand: 'BRAND_NAME', date: 'Friday, September 19, 2025', status: 'Dirty', color: 'black' },
    { id: 8, batchId: 'CH227', brand: 'BRAND_NAME', date: 'Monday, September 22, 2025', status: 'Approve', color: 'green' },
    { id: 9, batchId: 'CH228', brand: 'BRAND_NAME', date: 'Monday, September 15, 2025', status: 'Approve', color: 'green' },
    { id: 10, batchId: 'CH238', brand: 'BRAND_NAME', date: 'Tuesday, September 9, 2025', status: 'Dirty', color: 'cyan' },
];
